### ISSUE TITLE
C'est pas responsable

### ISSUE THREAD

**Issue by kouinkouin** [Cryde/fatidique#8]
Le bouton "Créer un compteur fatidiqu" n'est pas centré, hors du cadre grisée, et semble tronqué sur la droite.
De plus, il manque un "e" à la fin de la phrase.
J'ai fais un Ctrl+F5 sur mon GSM, et ça ne change rien.
Ça sent l'indolence tout ça !

**Comment by kouinkouin** [comment]
![tmp_27600-screenshot_20170628-131811772414147](https://user-images.githubusercontent.com/3999492/27655493-e49d55ac-5c45-11e7-9eb6-4015a5acce39.png)

**Comment by Cryde** [comment]
Wahou effectivement un bug ! 
Quelle perspicacité !

**Comment by Cryde** [comment]
On production !
